version: '3.8'

services:
  readi-app:
    build:
      context: ./readi
      dockerfile: Dockerfile
    container_name: readi-app
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:xayqrbkhgwyjip1w@readi-readidb-kryqoa:5432/postgres
      - NEXTAUTH_SECRET=7xK9mP2vL5nQ8rT3wE6yU1iO4pA7sD0fG3hJ6kM9nB2vC5xZ8qW1eR4tY7uI0oL3pA6sD9fG2hK5jM8bN1vC4xZ7
      - NEXTAUTH_URL=https://app.readi.fr
    networks:
      - dokploy-overlay
networks:
  dokploy-overlay:
    external: true
    name: dokploy-overlay
